### ISSUE TITLE
segfault on 32-bit with 7.4.0RC1

### ISSUE THREAD

**Issue by remicollet** [zeromq/php-zmq#204]
Running test suite

```
TEST 23/64 [tests/023-failedcallback.phpt]
========DIFF========
007+ 
008+ Termsig=11
007- success
008- called just_echo
009- success
010- OK
========DONE========
FAIL Test that failing callback does not add socket to plist [tests/023-failedcallback.phpt] 

```

GDB bactrace
```
(gdb) bt
#0  0x56958aa7 in zend_objects_store_put (object=object@entry=0xf707e140) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_objects_API.c:148
#1  0x56954150 in _zend_object_std_init (ce=0x56fc7670, object=0xf707e140) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_objects.c:35
#2  zend_objects_new (ce=ce@entry=0x56fc7670) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_objects.c:198
#3  0x56942729 in zend_default_exception_new_ex (class_type=0x56fc7670, skip_top_traces=0) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_exceptions.c:209
#4  0x56924752 in _object_and_properties_init (properties=0x0, class_type=0x56fc7670, arg=0xf7014250) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_API.c:1406
#5  object_init_ex (arg=0xf7014250, class_type=0x56fc7670) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_API.c:1420
#6  0x56987e7b in ZEND_NEW_SPEC_CONST_UNUSED_HANDLER () at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_vm_execute.h:9195
#7  0x569a5161 in execute_ex (ex=0xfb800944) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_vm_execute.h:54231
#8  0x56913ec0 in zend_call_function (fci=0xffff9864, fci_cache=0xffff983c) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_execute_API.c:816
#9  0xf72e91ce in php_zmq_connect_callback (socket=<optimized out>, fci=fci@entry=0xffff9864, fci_cache=fci_cache@entry=0xffff983c, persistent_id=0xf70654b0)
    at /builddir/build/BUILD/php-pecl-zmq-1.1.3/NTS/zmq.c:618
#10 0xf72e9490 in zim_zmqsocket___construct (execute_data=0xf7014190, return_value=<optimized out>) at /usr/include/php/Zend/zend_types.h:442
#11 0x569ab513 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_vm_execute.h:1607
#12 execute_ex (ex=0xfb800944) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_vm_execute.h:53481
#13 0x569adba4 in zend_execute (op_array=0xf707e000, return_value=0x0) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend_vm_execute.h:57561
#14 0x569227dd in zend_execute_scripts (type=8, retval=0x0, file_count=3) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/Zend/zend.c:1663
#15 0x568bf54c in php_execute_script (primary_file=<optimized out>) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/main/main.c:2619
#16 0x569afe66 in do_cli (argc=62, argv=0x56f75680) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/sapi/cli/php_cli.c:961
#17 0x5678bb09 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/php-7.4.0~RC1-1.fc29.remi.i386/sapi/cli/php_cli.c:1352
```

**Comment by sergiorighi** [comment]
Have you had any success in php 7.4?

**Comment by zebastian** [comment]
@remicollet is fixed with latest commit, can you check again?

**Comment by remicollet** [comment]
Yes, master build ok on 7.4, and test suite passes,
BTW still some warnings, see pr #213
